# Generated by Django 3.0.3 on 2020-07-20 15:00

from django.db import migrations, models
import utils.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('title', models.CharField(max_length=32, verbose_name='标题')),
                ('web_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='推文链接')),
                ('image', models.ImageField(blank=True, default='carousel/default.jpg', storage=utils.storage.ImageStorage(), upload_to='carousel/%Y/%m/%d', verbose_name='图片')),
                ('status', models.SmallIntegerField(choices=[(0, '不显示'), (1, '显示')], default=0, verbose_name='状态')),
                ('carousel_type', models.SmallIntegerField(choices=[(0, '图片'), (1, '推文')], default=0, verbose_name='类型')),
                ('index', models.SmallIntegerField(default=1, verbose_name='索引顺序')),
            ],
            options={
                'verbose_name': '轮播图',
                'verbose_name_plural': '轮播图',
            },
        ),
        migrations.CreateModel(
            name='Tips',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('title', models.CharField(max_length=32, verbose_name='标题')),
                ('image', models.ImageField(blank=True, default='carousel/default.jpg', storage=utils.storage.ImageStorage(), upload_to='carousel/%Y/%m/%d', verbose_name='图片')),
                ('status', models.SmallIntegerField(choices=[(0, '不显示'), (1, '显示')], default=0, verbose_name='状态')),
                ('index', models.CharField(max_length=32, verbose_name='索引')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
