# Generated by Django 3.0.3 on 2020-07-20 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tips',
            options={'verbose_name': '贴士', 'verbose_name_plural': '贴士'},
        ),
        migrations.AlterField(
            model_name='carousel',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '不显示'), (1, '显示')], default=1, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='tips',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '不显示'), (1, '显示')], default=1, verbose_name='状态'),
        ),
    ]
