# Generated by Django 3.0.3 on 2020-07-21 04:37

from django.db import migrations, models
import utils.storage


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_auto_20200720_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tips',
            name='image',
            field=models.ImageField(blank=True, default='tips/default.jpg', storage=utils.storage.ImageStorage(), upload_to='tips/%Y/%m/%d', verbose_name='图片'),
        ),
    ]
