# Generated by Django 3.0.3 on 2020-07-21 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_auto_20200721_1237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carousel',
            old_name='web_url',
            new_name='web',
        ),
    ]
