# Generated by Django 3.0.3 on 2020-07-21 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0002_auto_20200721_1101'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': '用户表', 'verbose_name_plural': '用户表'},
        ),
    ]
